name: Security Scan and Report

on:
  push:
    branches:
      - "v[0-9]+.[0-9]+"
        
jobs:
  security_scan:
    if: ${{ !startsWith(github.event.head_commit.message,'#NORUN') }}
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-results.txt'
          exit-code: 1
          severity: 'CRITICAL,HIGH'
      

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

        


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: brian7788/cicd:${{github.sha}}
      - name: Sign image with a key
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "brian7788/cicd:${{github.sha}}"
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_MESSAGE: "Name: LIN BINGYI\n Matriculation number: A028622L\n Email: e1221834@u.nus.edu \n Repository: https://github.com/${{github.repository}} \n Docker Hub URL: https://hub.docker.com/repository/docker/brian7788/cicd/general"
          SLACK_TITLE: Post Title
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack Notification
        if: ${{failure()}}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_MESSAGE: 'Scan Failed'
          SLACK_TITLE: Post Title
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      
      - name: upload file
        if: ${{failure()}}
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          content: 'file content'
          file_type: 'text'
          file_name: './trivy-results.txt'
          title: 'title of file'
          initial_comment: 'post by slack-upload-file'

